config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  resources :plant_records
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/plant_record.rb
class PlantRecord < ApplicationRecord
  has_many_attached :photos
  validates :latitude, presence: true
  validates :longitude, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @plant_records = PlantRecord.all
  end
end

app/controllers/plant_records_controller.rb
class PlantRecordsController < ApplicationController
  before_action :set_plant_record, only: %i[ show edit update destroy ]

  # GET /plant_records or /plant_records.json
  def index
    @plant_records = PlantRecord.all
  end

  # GET /plant_records/1 or /plant_records/1.json
  def show
  end

  # GET /plant_records/new
  def new
    @plant_record = PlantRecord.new
  end

  # GET /plant_records/1/edit
  def edit
  end

  # POST /plant_records or /plant_records.json
  def create
    @plant_record = PlantRecord.new(plant_record_params)

    respond_to do |format|
      if @plant_record.save
        format.html { redirect_to @plant_record, notice: "Plant record was successfully created." }
        format.json { render :show, status: :created, location: @plant_record }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @plant_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plant_records/1 or /plant_records/1.json
  def update
    respond_to do |format|
      if @plant_record.update(plant_record_params)
        format.html { redirect_to @plant_record, notice: "Plant record was successfully updated." }
        format.json { render :show, status: :ok, location: @plant_record }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @plant_record.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plant_records/1 or /plant_records/1.json
  def destroy
    @plant_record.destroy
    respond_to do |format|
      format.html { redirect_to plant_records_url, notice: "Plant record was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_plant_record
    @plant_record = PlantRecord.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def plant_record_params
    params.require(:plant_record).permit(:latitude, :longitude, :notes, photos: [])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<script>
  function renderGoogleMaps() {
      const Guanajuato = { latitude: 21.1250, longitude: -101.6860};

      const mapProp= {
          center:new google.maps.LatLng(Guanajuato.latitude, Guanajuato.longitude),
          zoom: 5,
        };

      const map = new google.maps.Map(document.getElementById("map"),mapProp);

      let marker;
      <%- @plant_records.each_with_index do |plant_record, index| %>
        marker = new google.maps.Marker({
          position: { lat: <%= plant_record.latitude%>, lng: <%= plant_record.longitude %> },
          map: map,
          icon: {
            url: "<%= image_url("icons/#{"%03d" % (index.next % 50)}-tree.png")%>",
            scaledSize: new google.maps.Size(40, 40)
          }
        });

        marker.addListener("click", () => { location.href = "<%= plant_record_path plant_record  %>" });
      <% end%>
    }
</script>

<div id="map" data-component="map" style="width:100%;height:800px;"></div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <%= link_to 'Arboleo', root_path, class:"navbar-brand h1"%>
    <%= link_to 'Registros', plant_records_path, class:"navbar-text"%>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Arboleo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script async src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAPS_API_KEY']%>&callback=renderGoogleMaps"> </script>
  </head>

  <body>
    <div class="container bg-light p-4">
      <%= render 'layouts/navbar'%>
      <hr><br>
      <%= yield %>
    </div>
  </body>
</html>

app/views/plant_records/_form.html.erb
<%= form_with(model: plant_record) do |form| %>
  <% if plant_record.errors.any? %>
    <div  class="alert alert-warning">
      <h2 class="alert-heading"><%= pluralize(plant_record.errors.count, "error") %> prohibited this plant_record from being saved:</h2>

      <ul>
        <% plant_record.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="d-flex flex-column align-items-center card bg-success bg-gradient p-3">
    <i class="fas fa-camera fa-3x text-white"></i>
    <hr>
    <%= form.file_field :photos, multiple: true, class: "form-control" %>
  </div>

  <br/>

  <div class="row">
    <div class="btn btn-secondary" data-component="magic-location-fill">
      Auto-completar información geografica &nbsp;
      <i class="fas fa-hat-wizard"></i>
    </div>
  </div>

  <hr>

  <div class="form-floating mb-3">
    <%= form.text_field :latitude, class: "form-control"%>
    <%= form.label :latitude %>
  </div>

  <div class="form-floating mb-3">
    <%= form.text_field :longitude, class: "form-control" %>
    <%= form.label :longitude %>
  </div>

  <hr>

  <div class="form-floating mb-3">
    <%= form.text_area :notes, class: "form-control", style: "min-height: 200px" %>
    <%= form.label :notes %>
  </div>

  <br/>

  <div class="d-grid gap-2">
    <%= form.submit class: "btn btn-lg btn-success" %>
  </div>
<% end %>

app/views/plant_records/_photos.html.erb
<div id="carousel" class="carousel slide bg-secondary bg-gradient" data-bs-ride="carousel">
  <div class="carousel-inner">
    <%- photos.each_with_index do |photo, index| %>
      <div class="carousel-item <%= index.zero? && "active" %>">
        <div class="d-flex justify-content-center w-100">
          <div class="border border-5 w-75">
            <%= image_tag photo, class: "img-thumbnail"%>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carousel"  data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carousel"  data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/plant_records/edit.html.erb
<%= render 'form', plant_record: @plant_record %>

<hr>

<div class="text-center">
  <%= link_to 'Show', @plant_record, class: "btn btn-link"%>
  <%= link_to 'Back', plant_records_path, class: "btn btn-light" %>
</div>

app/views/plant_records/index.html.erb
<p class="<%= notice && "alert alert-success"%>"><%= notice %></p>

<h1>Records</h1>

<hr>

<div class="text-center">
  <%= link_to 'New Plant Record', new_plant_record_path, class: "btn btn-light" %>
</div>

<hr>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Longitude</th>
      <th scope="col">Latitude</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @plant_records.each do |plant_record| %>
      <tr>
        <th scope="row"> <i class="fas fa-<%= cycle("seedling", "leaf", "tree")%>"></i> </th>
        <td><%= plant_record.longitude.round(2) %></td>
        <td><%= plant_record.latitude.round(2) %></td>
        <td>
          <div class="dropdown">
            <button class="btn dropdown-toggle" type="button" id="dropdown<%= plant_record.id%>" data-bs-toggle="dropdown" aria-expanded="false">
              ...
            </button>
            <ul class="dropdown-menu" aria-labelledby="dropdown<%= plant_record.id %>">
              <li><%= link_to 'Show', plant_record, class: "dropdown-item"%></li>
              <li><%= link_to 'Edit', edit_plant_record_path(plant_record), class: "dropdown-item" %></li>
              <li><%= link_to 'Destroy', plant_record, class: "dropdown-item", method: :delete, data: { confirm: 'Are you sure?' } %></li>
            </ul>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/plant_records/new.html.erb
<%= render 'form', plant_record: @plant_record %>

<hr>

<div class="text-center">
  <%= link_to 'Back', plant_records_path, class: "btn btn-light" %>
</div>

app/views/plant_records/show.html.erb
<p class="<%= notice && "alert alert-success"%>"><%= notice %></p>

<%= render 'photos', photos: @plant_record.photos%>
<hr>
<dl class="row">
  <dt class="col-sm-3"><strong>Latitude:</strong></dt>
  <dd class="col-sm-9"><%= @plant_record.latitude%></dd>
  <hr>
  <dt class="col-sm-3"><strong>Longitude:</strong></dt>
  <dd class="col-sm-9"><%= @plant_record.longitude%></dd>
  <hr>
  <dt class="col-sm-3"><strong>Notes:</strong></dt>
  <dd class="col-sm-9"><%= @plant_record.notes%></dd>
  <hr>
  <dt class="col-sm-3"><strong>Created at:</strong></dt>
  <dd class="col-sm-9"><%= @plant_record.created_at%></dd>
</dl>

<hr>

<div class="text-center">
  <%= link_to 'Edit', edit_plant_record_path(@plant_record), class: "btn btn-link"%>
  <%= link_to 'Back', plant_records_path, class: "btn btn-light" %>
</div>